//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	public enum StatusDisparo
	{
        Nenhum = 0,
        NaoIniciado = 1,
        EmProcessamento = 2,
        Enviado = 3,
        Erro = 4,
        TempoExcedido = 5
	}
}