using System;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class AlertaInfo : ApplicationException
	{
        public AlertaInfo(string causa, TipoAlerta tipo)
        {
            this.Origem = causa;
            this.Tipo = tipo;
        }

        public AlertaInfo(string causa, TipoAlerta tipo, Exception ex)
            : base(ex.Message, ex)
        {
            this.Origem = causa;
            this.Tipo = tipo;
        }

	    public int Codigo
		{ get; set; }

		public string Origem
		{ get; set; }

		public int CodigoUsuario
		{ get; set; }

		public string IP
		{ get; set; }
		
		public TipoAlerta Tipo
		{ get; set; }
	}
}