using System;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class AmbienteInfo
	{
		public AmbienteInfo()
		{ }

		public int Codigo
		{ get; set; }

		public string Apelido
		{ get; set; }

		public string NomeResponsavel
		{ get; set; }

		public string EmailResponsavel
		{ get; set; }

	}
}
