using System;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class CampanhaInfo
	{
		public CampanhaInfo()
		{ }

		public int Codigo
		{ get; set; }

		public int CodigoAmbiente
		{ get; set; }

        public int CodigoServidor
        { get; set; }

        public int CodigoRemetente
        { get; set; }

		public string Nome
		{ get; set; }

		public bool Ativo
		{ get; set; }

		public DateTime Criacao
		{ get; set; }

	}
}
