using System;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class ContatoInfo
	{
		public ContatoInfo()
		{ }

		public int Codigo
		{ get; set; }

        public int CodigoAmbiente
        { get; set; }

		public string Nome
		{ get; set; }

		public string Apelido
		{ get; set; }

		public string Email
		{ get; set; }

		public bool Ativo
		{ get; set; }

		public DateTime Criacao
		{ get; set; }

	}
}
