using System;
using System.Collections.Generic;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class DisparoInfo
	{
		public DisparoInfo()
		{
		    Destinatarios = new List<DestinatarioInfo>();
            Mensagem = new MensagemInfo();
		}

		public int Codigo
		{ get; set; }

		public int CodigoMensagem
		{ get; set; }

        public int CodigoAmbiente
        { get; set; }

		public DateTime InicioAgendamento
		{ get; set; }

		public DateTime TerminoAgendamento
		{ get; set; }

		public DateTime InicioDisparo
		{ get; set; }

		public DateTime TerminoDisparo
		{ get; set; }

		public bool Ativo
		{ get; set; }

		public DateTime Criacao
		{ get; set; }

		public int CodigoRemetente
		{ get; set; }

		public StatusDisparo StatusDisparo
		{ get; set; }

        public IList<DestinatarioInfo> Destinatarios
        { get; set; }

        public int TotalDestinatarios
        { get; set; }

        public MensagemInfo Mensagem
        { get; set; }
	}
}
