using System;
using System.Collections.Generic;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class GrupoInfo
	{
		public GrupoInfo()
		{
		    Contatos = new List<ContatoInfo>();
		}

		public int Codigo
		{ get; set; }

        public int CodigoAmbiente
        { get; set; }

		public string Nome
		{ get; set; }

		public bool Ativo
		{ get; set; }

		public DateTime Criacao
		{ get; set; }

	    public bool Sistema
        { get; set; }

        public IList<ContatoInfo> Contatos
        { get; set; }
	}
}