using System;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class LinkParametroRastreamentoInfo
	{
		public LinkParametroRastreamentoInfo()
		{ }

		public int CodigoLink
		{ get; set; }

		public int CodigoParametroRastreamento
		{ get; set; }

        public string Nome
        { get; set; }

		public string Valor
		{ get; set; }

	}
}
