using System;
using System.Collections.Generic;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class MensagemInfo
	{
		public MensagemInfo()
		{
		    this.Campanha = new CampanhaInfo();
            this.Variaveis = new List<VariavelInfo>();
		}

		public int Codigo
		{ get; set; }

        public int CodigoAmbiente
        { get; set; }

		public CampanhaInfo Campanha
		{ get; set; }

		public string Nome
		{ get; set; }

		public string Assunto
		{ get; set; }

		public string HTML
		{ get; set; }

		public bool Ativo
		{ get; set; }

		public DateTime Criacao
		{ get; set; }

        public TipoMensagem Tipo
        { get; set; }

        public int TotalDisparos
        { get; set; }

        public IList<VariavelInfo> Variaveis
        { get; set; }
	}
}
