using System;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class ParametroRastreamentoInfo
	{
		public ParametroRastreamentoInfo()
		{ }

		public int Codigo
		{ get; set; }

		public string Nome
		{ get; set; }

	}
}
