using System;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class RemetenteInfo
	{
		public RemetenteInfo()
		{ }

		public int Codigo
		{ get; set; }

		public int CodigoAmbiente
		{ get; set; }

		public string Email
		{ get; set; }

		public string Nome
		{ get; set; }

		public string Apelido
		{ get; set; }

		public DateTime Criacao
		{ get; set; }

		public bool Padrao
		{ get; set; }

	}
}