using System;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class ServidorInfo
	{
		public ServidorInfo()
		{ }

		public int Codigo
		{ get; set; }

		public int CodigoAmbiente
		{ get; set; }

		public string Apelido
		{ get; set; }

		public string Endereco
		{ get; set; }

		public int Porta
		{ get; set; }

		public string Usuario
		{ get; set; }

		public string Senha
		{ get; set; }

		public bool SSL
		{ get; set; }

        public bool Padrao
        { get; set; }
	}
}
