using System;
using System.Collections.Generic;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class VariavelInfo
	{
		public VariavelInfo()
		{
		    Valores = new List<VariavelValorInfo>();
		}

		public int Codigo
		{ get; set; }

		public int CodigoMensagem
		{ get; set; }

		public string Nome
		{ get; set; }

        public bool Ativo
        { get; set; }

        public bool Sistema
        { get; set; }

        public IList<VariavelValorInfo> Valores
        { get; set; }
	}
}
