using System;

//Auto generated by CodeProvider 3.0
namespace SimpleCode.MailSender.Model
{
	[Serializable]
	public class VisitaLinkInfo
	{
		public VisitaLinkInfo()
		{ }

		public int CodigoDisparo
		{ get; set; }

		public int CodigoContato
		{ get; set; }

		public int CodigoLink
		{ get; set; }

		public int Visitas
		{ get; set; }

		public string PrimeiraVisita
		{ get; set; }

	}
}
